"use client";

import { useEffect, useState } from "react";
import { VisitationService } from "@/features/visitations/services/visitation.service";
import { Printer, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";

export default function PrintVisitationList() {
  const router = useRouter();
  const [visitations, setVisitations] = useState<any[]>([]);

  useEffect(() => {
    async function load() {
      const data = await VisitationService.getAll().catch(() => []);
      setVisitations(data);
    }
    load();
  }, []);

  return (
    <div className="p-8 max-w-4xl mx-auto space-y-6 bg-white min-h-screen">
      {/* Print Trigger Header */}
      <div className="flex items-center justify-between border-b pb-4 print:hidden">
        <Button variant="outline" onClick={() => router.back()} className="flex items-center gap-2 text-xs">
          <ArrowLeft size={14} /> Back to App
        </Button>
        <Button onClick={() => window.print()} className="flex items-center gap-2 bg-blue-600 text-white text-xs">
          <Printer size={14} /> Print Schedule Sheet
        </Button>
      </div>

      {/* Printable Sheet Content */}
      <div className="space-y-4">
        <div className="text-center border-b pb-4 space-y-1">
          <h1 className="text-xl font-bold uppercase text-gray-900">The Church of Pentecost — Buoho District</h1>
          <h2 className="text-base font-semibold text-blue-800">Pastoral Home Visitation Schedule Sheet</h2>
          <p className="text-xs text-gray-500">
            District Pastor: Pastor Thomas Appiah • Visitation Hours: 4:00 PM – 6:30 PM
          </p>
        </div>

        <table className="w-full border-collapse border text-left text-xs">
          <thead>
            <tr className="bg-gray-100 border-b">
              <th className="border p-2 font-bold">#</th>
              <th className="border p-2 font-bold">Member Name</th>
              <th className="border p-2 font-bold">Phone Number</th>
              <th className="border p-2 font-bold">Local Assembly</th>
              <th className="border p-2 font-bold">Landmark / Residence</th>
              <th className="border p-2 font-bold">Visitation Notes & Prayer Needs</th>
            </tr>
          </thead>
          <tbody>
            {visitations.length === 0 ? (
              <tr>
                <td colSpan={6} className="border p-4 text-center text-gray-500">
                  No visits queued for printing.
                </td>
              </tr>
            ) : (
              visitations.map((v, i) => (
                <tr key={v.id} className="border-b">
                  <td className="border p-2 font-semibold">{i + 1}</td>
                  <td className="border p-2 font-bold text-gray-900">
                    {v.member ? `${v.member.firstName} ${v.member.lastName}` : "Member"}
                  </td>
                  <td className="border p-2">{v.member?.phone || "—"}</td>
                  <td className="border p-2">{v.member?.local?.name || "Buoho Central"}</td>
                  <td className="border p-2">{v.member?.areaLandmark || v.member?.address || "Landmark Pending"}</td>
                  <td className="border p-2 h-12"></td>
                </tr>
              ))
            )}
          </tbody>
        </table>

        <div className="pt-8 flex justify-between text-[11px] text-gray-500 border-t">
          <p>Generated by Buoho District Member Visitation Coordination System</p>
          <p>Date Generated: {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  );
}